version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    image: zemfus/barbot:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data:
