telegram:
  token: "6920173471:AAGuHIpVwkI9v9Si4vJ9BjT87nOoIUuNeNg"
#  token: "7330713969:AAFjCjXH9Lkt24pAD4fmNkJItp0vaZ6zzz8"
  debug: true
database:
  host: "postgres"
  port: 5432
  userName: "bot"
  password: "bot"
  dbName: "bot"
  migrationsPath: "migrations/"
app:
  superUserID:
    - 458912081
#    - 1347179916
    - 5250272087

