telegram:
  token: "7267347931:AAGYkgQ5lZq-5U4fTDRNtLzoZ9N0Ab_xrQs"
  debug: true
database:
#  host: "localhost"
  host: "postgres"
  port: 5432
  userName: "bot"
  password: "bot"
  dbName: "bot"
  migrationsPath: "migrations/"
app:
  adminID: 1071943210
  barmenID: 2120829752

