telegram:
  token: "7340728779:AAEgZPhXmxEvA6bUn6ytMzUezRsc507JaDU" # prod
  debug: true
database:
#  host: "localhost"
  host: "postgres"
  port: 5432
  userName: "bot"
  password: "bot"
  dbName: "bot"
  migrationsPath: "migrations/"
app:
  adminID: 1071943210 # prod
#  adminID : 0
#  barmenID: 1071943210
  barmenID: 2120829752 # prod
#  barmenID: 1400299119 # test
#  barmenID: 0
  chatID: -1002169957134

