telegram:
  token: "7168888189:AAE4tHLkY-Uzf3LYL2N9lK36k_LGJVlOZW8"
  debug: true
database:
  host: "localhost"
  port: 5432
  userName: "bot"
  password: "bot"
  dbName: "bot"
  migrationsPath: "migrations/"
app:
  superUserID: 5250272087

